version: "3.9"

services:
  api:
    build: .
    container_name: api_dockerizing
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./db/migrations:/db/migrations
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - fullstack

  postgres:
    image: postgres:latest
    container_name: postgres_dockerizing
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_DB}"
      DB_SSLMODE: "${DB_SSLMODE}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - database_dockerizing:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  database_dockerizing:

networks:
  fullstack:
    driver: bridge

